### ISSUE TITLE
Running on SUPERB

### ISSUE THREAD

**Issue by Hguimaraes** [glory20h/CompressW2V2#3]
Hi everyone,

First, thank you so much for opening this repo and sharing it with us! FitHuBERT is a very important paper for the S3RL community.

I was having a hard time trying to use your model in the SUPERB benchmark.
As mentioned in the README, I moved the fithubert folder to the upstream folder of the S3PRL repo, and when I was about to run for some downstream tasks (e.g., ASR), some problems arose.

First:

```bash
[Runner] - Start a new experiment
[Featurizer] - Take a list of 12 features and weighted sum them.
Traceback (most recent call last):
  File "/home/heitor/projects/robust_s3prl/s3prl/run_downstream.py", line 241, in <module>
    main()
  File "/home/heitor/projects/robust_s3prl/s3prl/run_downstream.py", line 236, in main
    runner = Runner(args, config)
  File "/home/heitor/projects/robust_s3prl/s3prl/downstream/runner.py", line 102, in __init__
    self.featurizer = self._get_featurizer()
  File "/home/heitor/projects/robust_s3prl/s3prl/downstream/runner.py", line 198, in _get_featurizer
    model = Featurizer(
  File "/home/heitor/projects/robust_s3prl/s3prl/upstream/interfaces.py", line 180, in __init__
    feature = self._weighted_sum([f.cpu() for f in feature])
  File "/home/heitor/projects/robust_s3prl/s3prl/upstream/interfaces.py", line 180, in <listcomp>
    feature = self._weighted_sum([f.cpu() for f in feature])
AttributeError: 'tuple' object has no attribute 'cpu'
```

This is because FitHuBERT is returning a tuple (x, attn, layer_result) to the hidden_state. I think it is okay; I could change the code to take only the layer_result, for instance (This is what you do in your paper?).

Another problem is related to the dimensions of the output.
Due to the time-reduction factor, the pretrained model returns a representation with half of the expected size. When passing the hidden state, how do you handle this? Because some of the SUPERB tasks are expecting a downsample_rate of 320.

Any tips here would help a lot.

Best,

**Comment by glory20h** [comment]
Hi, thank you for your interest on FitHuBERT.

Sorry my bad, you need to add `-s last_hidden_state` argument for the command to work properly. I updated the README.md file accordingly.

Regarding your question on the dimensions of the output, there is an upsampler in the prediction head after the last layer that restores the downsample_rate. Due to this, we can use the same downsample_rate of 320.

**Comment by Hguimaraes** [comment]
Thank you so much! I'm able to run the code. I'm closing the issue now.
